module.exports = [
  "North Vancouver",
  "Vernon",
  "Nanaimo",
  "Nelson",
  "New Westminster",
  "Delta",
  "Burnaby",
  "Surrey",
  "Coquitlam",
  "Vancouver",
  "Errington",
  "Parksville",
  "Penticton",
  "Pitt Meadows",
  "Port Coquitlam",
  "Port Alberni",
  "Port Moody",
  "Powell River",
  "Prince George",
  "Quesnel",
  "Richmond",
  "Rossland",
  "Salmon Arm",
  "Terrace",
  "Victoria",
  "Kelowna",
  "White Rock",
  "Blaine",
  "Williams Lake",
  "Maple Ridge",
  "Oak Bay",
  "Gabriola",
  "Qualicum Beach",
  "Nanoose Bay",
  "Langley",
  "Anmore",
  "Revelstoke",
  "Canoe",
  "Trail",
  "West Kelowna",
  "West Vancouver",
  "Mission Indian Reserve 1",
  "Mission BC",
  "Barnston Island",
  "Langley Township",
];
