module.exports = [
  "Whalley",
  "Central Vancouver",
  "Grandview-Woodland",
  "Strathcona",
  "East Vancouver",
  "Burke Mountain",
  "Marpole",
  "Sunset",
  "Oakridge",
  "Kerrisdale",
  "South Newton",
  "Newton",
  "Fairview",
  "Granville Island",
  "Riley Park–Little Mountain",
  "South Main",
  "Downtown",
  "Rockland",
  "Jubilee",
  "Gonzales",
  "James Bay",
  "Harris Green",
  "Fernwood",
  "North Park",
  "Burnside",
  "South Pandosy - K.L.O.",
  "Cultural District",
  "Chinatown",
  "Guildford",
  "Steveston",
  "East Newton South",
  "Cloverdale",
  "Knight",
  "Fairfield",
  "Jubilee South",
  "Oaklands",
  "Hillside - Quadra - Downtown Blanshard",
  "South Surrey",
  "South Westminster",
  "Haney",
  "Rosemary Heights West",
  "Rosemary Heights Central",
  "Rosemary Heights Business Park",
  "North Grandview Heights",
  "Shaughnessy",
  "Kitsilano",
  "Dunbar-Southlands",
  "South Cambie",
  "South Central",
  "Central City",
  "Hammond",
  "Westwood Plateau",
  "East Newton Business Park",
  "West Cloverdale South",
  "Arbutus Ridge",
  "Mount Pleasant",
  "West Newton South",
  "Downtown Vancouver",
  "North Mission - Crawford",
  "South",
  "Victoria West",
  "Morgan Crossing",
  "Grandview Heights",
  "Southlands",
  "East Newton North",
  "Surrey Newton",
  "Morgan Heights",
  "Jubilee North",
];
