// https://developers.google.com/maps/documentation/places/web-service/supported_types
module.exports = [
  // "airport",
  // "amusement_park",
  // "aquarium",
  // "art_gallery",
  // "atm",
  "bakery",
  // "bank",
  // "bar",
  // "bicycle_store",
  // "book_store",
  // "bowling_alley",
  // "bus_station",
  "cafe",
  // "campground",
  // "car_rental",
  // "casino",
  // "clothing_store",
  // "convenience_store",
  // "gas_station",
  // "gym",
  // "hospital",
  // "laundry",
  // "library",
  // "light_rail_station",
  "lodging",
  // "meal_takeaway",
  // "movie_theater",
  // "museum",
  // "park",
  // "parking",
  "restaurant",
  // "shopping_mall",
  // "spa",
  // "stadium",
  // "store",
  // "subway_station",
  // "supermarket",
  // "taxi_stand",
  "tourist_attraction",
  // "train_station",
  // "transit_station",
  // "travel_agency",
  // "university",
  // "zoo",
];
